### ISSUE TITLE
Empty Rating 

### ISSUE THREAD

**Issue by amruta1625** [RushikeshChary/KnowYourCibo#22]
we are able to rate the dish with zero stars which shouldn't be happening as minimum rating starts from 1.

**Comment by HavisH-R** [comment]
It's upto us.

**Comment by amruta1625** [comment]
Its upto you to implement whatever you wanted, but we have to tell you the major issues from a user point of view. however, zero rating is still not a good practice as it doesn't make sense whether you have rated or you just randomly clicked rate.

**Comment by amruta1625** [comment]
Even if you think its upto you to give zero rating then you should implement it in such a way you could change the rating to zero but what I can see is it could be minimum of one star when user clicked on the stars. And here the logic of giving zero rating is failed.

**Comment by HavisH-R** [comment]
As u quoted "you should implement it in such a way you could change the rating to zero" .Again it's just a matter of choice, the way I see it selecting nothing is equivalent to zero rating.Anyways thank you for your suggestion.

**Comment by amruta1625** [comment]
you are welcome. but I guess you didn't understand what I have meant. And what exactly I mean to say is when user clicked for 4 stars he could change it to 2 stars or 1 star but not to a zero rating and I guess its not any matter of choice but a potential issue when you are considering a thing like zero rating to exist.

**Comment by HavisH-R** [comment]
Yes, Thanks for pointing out . Now, the minimum rating starts from 1 (modified considering your suggestion).I Think that fixes the issue.  thank u.
