### ISSUE TITLE
Edit profile(change password)

### ISSUE THREAD

**Issue by amruta1625** [RushikeshChary/KnowYourCibo#25]
While changing the password in profile page it is mentioned to use more than 8 characters, however it is not used anywhere. you can implement the code logic to take only such kind of passwords.

**Comment by RushikeshChary** [comment]
"Use 8 or more characters with a mix of letters, numbers, and symbols to be more secure."
-This is the statement shown at that location. Clearly, it only suggests the user.

**Comment by amruta1625** [comment]
okkk
