### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by nrithika** [RushikeshChary/KnowYourCibo#26]
When you search for an item and go to the item view, the navbar is getting disappeared in a few cases in small screen laptops
![IMG-20240407-WA0020](https://github.com/RushikeshChary/KnowYourCibo/assets/134864481/48d549cc-0638-4e35-a134-e105ac5604d9)

**Comment by RushikeshChary** [comment]
@idiotic13 
- Suggestion:
    Put a scroll option on the entire restaurant page.
